[package]
name = "nwr"
version = "0.5.6"
authors = ["wang-q <wang-q@outlook.com>"]
description = "`nwr` is a command line tool for newick and taxonomy"
documentation = "https://github.com/wang-q/nwr"
homepage = "https://github.com/wang-q/nwr"
repository = "https://github.com/wang-q/nwr"
readme = "README.md"
categories = ["command-line-utilities", "text-processing", "bioinformatics"]
license = "MIT"
edition = "2018"

[badges]
travis-ci = { repository = "wang-q/nwr", branch="0.5.6" }
appveyor = { repository = "wang-q/nwr" }

[[bin]]
name = "nwr"
path = "src/nwr.rs"

[dependencies]
clap = { version = "3.1.1", features = ["derive", "cargo"] }
regex = "1"
lazy_static = "1.3.0"
flate2 = "1.0"
itertools = "0.10.3"
bio = "0.30.0"

intspan = "^0.6.1"

ftp = "3"
tar = "0.4"
dirs = "4.0.0"
log = "0.4"
simplelog = "^0.10.0"
md5 = "^0.7.0"
rusqlite = { version = "0.26.3", features = ["bundled"] }
csv = "1.1"

[build-dependencies]

[dev-dependencies]
tempfile = "3.1.0"
assert_cmd = "0.11"
predicates = "1"

[profile.release]
lto = true
